# Configure variables for this example and build using generic makefile

APP_NAME           = UseDebugServer
APP_FORM           = UseDebugServerForm
XL                 = 0
ENGINE             = 1

include make.dotnet

