# Configure variables for this example and build using generic makefile

APP_NAME           = MultiThreadingTwoWindows
APP_FORM           = MultiThreadingTwoWindowsForm
XL                 = 0
ENGINE             = 1

include make.dotnet

