# Configure variables for this example and build using generic makefile

APP_NAME           = UseJitCompiler
APP_FORM           = UseJitCompilerForm
XL                 = 0
ENGINE             = 1

include make.dotnet

