# Configure variables for this example and build using generic makefile

APP_NAME           = ErrorHandling
APP_FORM           = ErrorHandlingForm
XL                 = 0
ENGINE             = 1

include make.dotnet

