# Configure variables for this example and build using generic makefile

APP_NAME           = UseVectorVariables
APP_FORM           = UseVectorVariablesForm
XL                 = 0
ENGINE             = 1

include make.dotnet

